### ISSUE TITLE
Subprocess.py error on keystore creation

### ISSUE THREAD

**Issue by ghost** [clugh/coc-patcher#4]
When I run: python3.5 patcher.py --json config.json
I get:

Getting config ...
Checking environment ...
client.keystore does not exist. Would you like to create it? (y/n): y
Traceback (most recent call last):
  File "patcher.py", line 126, in <module>
    result = subprocess.run([config['paths']['keytool'], '-genkey', '-keystore', KEYSTORE_PATH, '-storepass', config['keystore']['storepass'], '-alias', config['keystore']['key']['alias'], '-keypass', config['keystore']['key']['keypass'], '-dname', dname, '-keyalg', 'RSA', '-keysize', '2048', '-validity', '10000'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

Any ideas for a fix?

**Comment by ghost** [comment]
This is my config.json. all the paths are in my $PATH variable in bash
{
  "debug": false,
  "package": "com.supercell.clashofclans",
  "key": "41 02 C2 81 89 89 7A 48 CE DF A8 C6 E5 37 8F 55 62 4F 9E 84 08 FA 8A 37 66 43 DB BC E7 15 B2 1A",
  "url": "gamea.clashofclans.com",
  "keystore": {
    "storepass": "plenix",
    "key": {
      "alias": "PlenixClash",
      "keypass": "plenix",
      "dname": {
        "cn": "PlenixClash",
        "ou": "COC",
        "o": "PlenixClash",
        "l": "International",
        "s": "International",
        "c": "International"
      }
    }
  },
  "paths": {
    "apktool": "",
    "md5sum": "",
    "dd": "",
    "keytool": "",
    "jarsigner": "",
    "zipalign": ""
  }
}

**Comment by swasthikshetty1** [comment]
Fill the below details.

Example: 

"apktool":"C:\\apktool\\apktool.bat"
},
"paths": {
"apktool": "",
"md5sum": "",
"dd": "",
"keytool": "",
"jarsigner": "",
"zipalign": ""
}
}
